name: tankerkoenig_dart
description: |
  A dart package to retrieve data from german tankerkoenig v4 API.
  Get petrol stations, gas prices and the corresponding location 
  from their API.
version: 1.0.2
repository: https://github.com/jayjah/tankerkoenig_dart
homepage: https://markus.jayjah.de
issue_tracker: https://github.com/jayjah/tankerkoenig_dart/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  chopper: ^5.1.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
  chopper_generator: any
  build_runner: any
  dart_code_metrics: ^5.0.1