name: tankerkoenig_dart
description: |
  A dart package to retrieve data from german tankerkoenig v4 API.
  Get petrol stations, gas prices and the corresponding location 
  from their API.
version: 0.0.1
repository: https://github.com/jayjah/tankerkoenig_dart
homepage: https://markus.jayjah.de
issue_tracker: https://github.com/jayjah/tankerkoenig_dart/issues

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  chopper: ^4.0.5

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.2
  chopper_generator: any
  build_runner: any